<?php
/*
 * The MIT License
 *
 * Copyright 2016 vConnect.dk
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * @category Magento
 * @package Vconnect_AllInOne
 * @author vConnect
 * @email kontakt@vconnect.dk
 * @template app/design/frontend/base/default/template/vconnect/aio/dk/home/scripts.phtml
 */
?>

<script>
    window.pointsEndpoint = "<?php echo $this->getUrl('aio/index/index', array('_secure' => true))?>";

   <?php if (Mage::app()->getRequest()->getControllerModule() == 'Avenla_KlarnaCheckout'): ?>
   var aio_shipping_method_name = 'estimate_method';
   <?php else: ?>
   var aio_shipping_method_name = 'shipping_method';
   <?php endif; ?>

    jQuery(function($){
        var shipContryVal = $('select[name="shipping[country_id]"]:last').val();
        var shipPostcodeVal = $('input[name="shipping[postcode]"]:last').val();
        var shipStreetVal = $('input[name="shipping[street][]"]:first').val();
        var billContryVal = $('select[name="billing[country_id]"]:last').val();
        var billPostcodeVal = $('input[name="billing[postcode]"]:last').val();
        var billStreetVal = $('input[name="billing[street][]"]:first').val();

        if (($('#onestepcheckout-form').length > 0 || $('.opc-wrapper-opc').length > 0) && $('input[name="billing[use_for_shipping]"]').length > 0 && $('input[name="billing[use_for_shipping]"]').is(':checked')) {
           shipContryVal = '';
           shipPostcodeVal = '';
           shipStreetVal = '';
        }

        var country_id  = (shipContryVal !== '')?shipContryVal:billContryVal;
        var postcode  = (shipPostcodeVal !== '')?shipPostcodeVal:billPostcodeVal;
        var street  = (shipStreetVal !== '')?shipStreetVal:billStreetVal;

        var html_nearest_point = '';

        if ($('.nearest_point_container').length > 0) {
            getPickupPoints(country_id,postcode,street,function (points) {
                var nearest_point_monFriOpen = (typeof points[0].openingHours !== 'undefined')
                    ?points[0].openingHours[0].from1.insertString(2, 0, ":"):'';
                var nearest_point_monFriClose = (typeof points[0].openingHours !== 'undefined')
                    ?points[0].openingHours[0].to1.insertString(2, 0, ":"):'';
                var nearest_point_satOpen = (typeof points[0].openingHours !== 'undefined')
                    ?points[0].openingHours[points[0].openingHours.length-1].from1.insertString(2, 0, ":"):'';
                var nearest_point_satClose = (typeof points[0].openingHours !== 'undefined')
                    ?points[0].openingHours[points[0].openingHours.length-1].to1.insertString(2, 0, ":"):'';

                html_nearest_point = '<div class="aino-nearest-data">';
                html_nearest_point += '<div class="aino-nearest-name">' +points[0].name + '</div>';
                html_nearest_point += '<div class="aino-nearest-address">' + points[0].deliveryAddress.streetName + ', ' + points[0].deliveryAddress.streetNumber + '</div>';
                html_nearest_point += '<div class="aino-work-hours">' +
                        '<?php echo $this->__('Mon'); ?>-<?php echo $this->__('Fri'); ?>: '+nearest_point_monFriOpen +' - '+ nearest_point_monFriClose +'<br/>' +
                        '<?php echo $this->__('Sat'); ?>: '+nearest_point_satOpen +' - '+ nearest_point_satClose +
                        '</div>';
                html_nearest_point += '</div>';
                $('.nearest_point_container').show().find('.vc-value').html(html_nearest_point);
            });
        }

        function getPickupPoints(country_id,postcode,street,callback)
        {
            var dataToSend = {
                country_id  : country_id,
                postcode    : postcode
            };
            if(street){
                dataToSend.street = street;
            }
            $.ajax({
                url     : pointsEndpoint,
                data    : dataToSend
            }).done(function (data) {

                if( typeof data.postnord.servicePointInformationResponse === 'undefined')
                {
                    if( typeof data.postnord.message !== 'undefined'){
                        console.error(data.postnord.message);
                    }
                    return console.log('Pickup api\'s return unknown error');
                }
                var points = data.postnord.servicePointInformationResponse.servicePoints;

                if(callback) {
                    callback(points);
                }
            });
        }

        $('select[name="<?php echo $this->getCode()?>_arrival"],select[name="<?php echo $this->getCode()?>_delivery"]').on('change',function(){
            if (jQuery("input[name="+aio_shipping_method_name+"]:checked").length != 0 && jQuery("input[name="+aio_shipping_method_name+"]:checked").val().indexOf('vconnect_postnord_') != -1) {
                var desc = '';
                var otherText = '';

                var arrival = jQuery('select[name="'+jQuery("input[name="+aio_shipping_method_name+"]:checked").val()+'_arrival"]');
                if(arrival.length){
                    desc += ('' + arrival.val()); 
                }

                var delivery = jQuery('select[name="'+jQuery("input[name="+aio_shipping_method_name+"]:checked").val()+'_delivery"]');
                if(delivery.length){
                    desc += (' / ' + delivery.val());
                    if(delivery.val() == "<?php echo Mage::helper('vc_aio')->__('Other place'); ?>" || delivery.val() == 'Utan kvittens (paketet ställs utanför dörren)'){
                        var otherText =  jQuery('textarea[name="'+jQuery("input[name="+aio_shipping_method_name+"]:checked").val()+'_other"]').val();
                        var escaped = jQuery('<div/>').text(otherText).html();
                        desc += (" - " + escaped);
                    }
                }

                var obj = {
                    code            : jQuery("input[name="+aio_shipping_method_name+"]:checked").val(),
                    arrival         : jQuery('select[name="'+jQuery("input[name="+aio_shipping_method_name+"]:checked").val()+'_arrival"]').length?jQuery('select[name="'+jQuery("input[name="+aio_shipping_method_name+"]:checked").val()+'_arrival"]').val():false,
                    delivery        : delivery.length?delivery.val():false,
                    other           : otherText,
                    flexdelivery    : false,
                    carrier         : '<?php echo $this->escapeHtml($this->getCarrierTitle())?>',
                    description     : desc
                };

                obj.environmental_fee = 0;
                if (jQuery('[name="vconnect_postnord_environmental_fee"]:checked').length != 0) {
                    obj.environmental_fee = 1;
                }

                jQuery('input[name=payment_ain_vconnect_postnord_data]').val(JSON.stringify(obj));
            }

            <?php if (Mage::app()->getRequest()->getControllerModule() == 'Avenla_KlarnaCheckout'): ?>
            // Start fixer for KlarnaCheckout
            $$('input:checked[name="estimate_method"]')[0].simulate('click');
            // End fixer for KlarnaCheckout
            <?php endif; ?>
        });

        $('div[data-code=<?php echo $this->getCode() ?>]').appendTo($('input[value=<?php echo $this->getCode() ?>]').parent());
    });
</script>