<?php
/*
 * The MIT License
 *
 * Copyright 2016 vConnect.dk
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * @category Magento
 * @package Vconnect_AllInOne
 * @author vConnect
 * @email kontakt@vconnect.dk
 * @template app/design/frontend/base/default/template/vconnect/aio/dk/home/tabHeader.phtml
 */
$config = $this->getConfig();
?>





<li class="aino-office-tab" data-code="<?php echo $this->getCode() ?>">
    <a href="#post-office" class="cf pickup">
        <span>
            <?php echo $this->getMethodTitle() ?>
            <?php if(!empty($config['delivery_time'])): ?>
            <em><?php echo $config['delivery_time'] ?></em>
            <?php endif;?>
            <div class="aino-delivery-price"><?php echo $this->getPriceFormated() ?></div>
        </span>
    </a>


    <div class="tab-list aino-post-office cf aino-column" data-target="post-office">
        <div class="aino-map-container">
            <div class="aino-map"></div>
            <div class="zipcode-holder">
            <div class="post-code-input">
                <label>
                        <?php echo $this->__('Skift postnumber') ?>
                    <input type="text"/>
                </label>
                <button type="button"><span></span></button>
            </div>
            <div class="directions-display-type">
                <button role="DRIVING" type="button" class="aino-map-driving"><span></span></button>
                <button role="WALKING" type="button" class="aino-map-walking"><span></span></button>
                <button role="TRANSIT" type="button" class="aino-map-transit"><span></span></button>
            </div>
        </div>
        </div>
        <div class="address-near-you">
            <ul class="aino-nav">

            </ul>
        </div>
    </div>   

</li>





